apiVersion: v1
kind: Pod
metadata:
  name: dum-e-training

spec:
  restartPolicy: Never

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-A10
            - NVIDIA-RTX-A5000
            - NVIDIA-RTX-A6000
            - NVIDIA-GeForce-RTX-3090
            - NVIDIA-GeForce-RTX-4090

  containers:
  - name: dum-e-training

    image: vanshrai/dum_e_train:v0

    command: ["bash", "-c", "sleep infinity"]

    resources:
      requests:
        cpu: "2"
        memory: "8Gi"
        nvidia.com/gpu: 1

      limits:
        cpu: "2"
        memory: "8Gi"
        nvidia.com/gpu: 1

    volumeMounts:
    - name: data
      mountPath: /pvc

  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: streamvln-pvc
